@TouringChecker_HostAddress = https://localhost:7009

# GET {{TouringChecker_HostAddress}}/weatherforecast/
GET {{TouringChecker_HostAddress}}/api/weather/tomorrow?city=Tokyo

Accept: application/json

###

###
POST {{TouringChecker_HostAddress}}/api/weather/check
Content-Type: application/json
Accept: application/json

{
  "currentLocation":{
    "cityName": "Tokyo"
  }
}